### ISSUE TITLE
Add recipes for GeoCAT-f2py

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat_conda_recipes#7]
When it comes to integration, please add GeoCAT-f2py recipes here, in order to have all recipes here as documented.

- Despite deprecating GeoCAT-ncomp and libncomp, we may or may not keep recipes of them here.

**Comment by pilotchute** [comment]
Nope, we definately want to move all recipes into their repos. then we can delete this repo since it doesn't do anything other than complicate the build process.

**Comment by pilotchute** [comment]
Closing this issue per consensus.
